'use client';
import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { colours, imageFor, money, type Product, type ColourId } from '@/lib/catalogue';
import { useCart } from './cart-provider';
import { GarmentViewer } from './garment-viewer';
export function ProductOptions({ product, initialColour }: { product: Product; initialColour: ColourId }) {
  const [colour, setColour] = useState(initialColour), [size, setSize] = useState(''), [quantity, setQuantity] = useState(1), [error, setError] = useState(''), [message, setMessage] = useState(''), [view, setView] = useState<'photo' | '3d'>('3d');
  const { add, ready } = useCart();
  function addToBag() {
    setMessage(''); if (!size) { setError('Choose your size first.'); return; }
    if (!Number.isInteger(quantity) || quantity < 1 || quantity > 10) { setError('Choose a quantity from 1 to 10.'); return; }
    try { add({ id: product.id, colour, size, quantity }); setError(''); setMessage(`Added ${quantity} × ${product.name}, ${colours[colour].name}, size ${size}.`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not add this item.'); }
  }
  return <div className="product-page"><div><div className="product-preview-tabs" role="group" aria-label="Product view"><button type="button" aria-pressed={view === '3d'} onClick={() => setView('3d')}>3D garment</button><button type="button" aria-pressed={view === 'photo'} onClick={() => setView('photo')}>Product photo</button></div>{view === '3d' ? <GarmentViewer product={product} colour={colour} onColour={setColour} /> : <div className="detail-image"><Image id="detail-image" src={imageFor(product, colour)} alt={`${product.name} in ${colours[colour].name}`} width={600} height={750} sizes="(max-width:700px) 90vw, 50vw" unoptimized priority /></div>}<p className="sample-price">3D shape and print placement are illustrative. Product photos show the original design concepts.</p></div><div className="dialog-copy"><p className="eyebrow">{product.collection} / {product.type}</p><h1>{product.name}</h1><p className="detail-price">{money(product.price)}</p><p className="sample-price">Sample price · Nothing for sale</p><p>{product.description}</p><fieldset><legend>Colour: <span id="selected-colour">{colours[colour].name}</span></legend><div id="colour-options" className="colour-options">{product.colours.map(c => <button key={c} className="swatch" type="button" data-colour={c} aria-label={colours[c].name} aria-pressed={colour === c} style={{ '--swatch': colours[c].hex } as React.CSSProperties} onClick={() => { setColour(c); setMessage(''); }} />)}</div></fieldset><fieldset><legend>{product.type === 'Cargos' ? 'Waist size (inches)' : 'Select size'}</legend><div className="size-options" id="size-options">{product.sizes.map(s => <button key={s} type="button" data-size={s} aria-pressed={size === s} onClick={() => { setSize(s); setError(''); }}>{s}</button>)}</div></fieldset><label className="quantity-label" htmlFor="product-quantity">Quantity <input id="product-quantity" type="number" min="1" max="10" value={Number.isNaN(quantity) ? '' : quantity} onChange={e => setQuantity(e.target.valueAsNumber)} inputMode="numeric" /></label><p id="product-error" className="error-text" role="alert">{error}</p><button id="add-to-bag" className="button add-button" type="button" disabled={!ready} onClick={addToBag}>Add to bag</button><p id="add-status" role="status">{message}</p><Link className="added-link" href="/bag">View your bag →</Link><details><summary>Design and delivery details</summary><p>This is a personal demo. Sizes and prices are examples; no stock, delivery or orders are promised. No payment will be collected in demo checkout.</p></details></div></div>;
}
